#!/bin/bash

help() {
cat << END
$0 [opciók]

 -q		Mai dátum kiírása formázva.
 -w	 	A korod kiszámítása.
 -e 		Egy random rossz dad joke mentése json-ba.
 -r <string>	megnézni mennyiszer szerepel az input amit megadsz a viccbe.
 -t  		About me.
 -z		Kiirja a dad joke ot, de előtte leellenőrni, hogy egyáltalán van-e.
 -u <string>	Megvizsgálja van-e olyan szó amit bekérsz.
 -i		Nemzetközi Űrállomás aktuális adata.
END
}

rolam(){
 echo "Mihály Balázs"
 echo "D05D90"
 exit
}

maidatum() {
  now=$(date +%Y-%m-%d/%T)
  echo  $now
  exit
}

kor() {
read -p "Add meg a születési éved: " year
read -p "Add meg a születési hónapod: " month

yearnow=$(date '+%Y')
monthnow=$(date '+%m')

agey=$(($yearnow-$year))
agem=$(($monthnow-$month))

if [ $agem -lt 0 ] ; then
   agem=$(($monthnow-$month+12))
else
   agem=$(($monthnow-$month))
fi
echo "$agey éves és $agem hónapos vagy!"
exit
}

while getopts :hqwer:tzu:io: PARAM
do
 case $PARAM in
  o)
   exit
   ;;
  h)
   help
   exit
   ;;
  q)
   maidatum
   ;;
  w)
   kor
   ;;
  e)
   curl -H "Accept: application/json" https://icanhazdadjoke.com/ -o respone.json
   exit
   ;;
  r)
   cat 'respone.json' | grep -o $OPTARG | wc -l
   exit
   ;;
  t)
   rolam
   ;;
  z)
   if [ ! -f respone.json ]
   then
     echo "Nem létezik"
   else
     cat respone.json | jq .joke 
   fi
   exit
   ;;
  u)
   cat respone.json | jq .joke | grep $OPTARG
   exit
   ;;
  i)
   curl http://api.open-notify.org/iss-now.json | jq '.'
   exit
   ;;
  :)
   echo "$OPTARG vár paramétert!"
   exit 1
   ;;
  *)
   echo "Érvénytelen paraméter!"
   exit 1
   ;;
 esac
done
shift $(($OPTIND-1))
