#!/bin/bash

help() {
cat << END
$0 [opciók]

 -q		Mai dátum kiírása formázva.
 -w	 	A korod kiszámítása.
 -m		Adatok szűrése, ip cím és hostname kiíratása.
 -o <ip>	Megadott ip címről adatok letöltése.
END
}

maidatum() {
  now=$(date +%Y-%m-%d/%T)
  echo  $now
  exit
}

kor() {
read -p "Add meg a születési éved: " year
read -p "Add meg a születési hónapod: " month

yearnow=$(date '+%Y')
monthnow=$(date '+%m')

agey=$(($yearnow-$year))
agem=$(($monthnow-$month))

if [ $agem -lt 0 ] ; then
   agem=$(($monthnow-$month+12))
else
   agem=$(($monthnow-$month))
fi
echo "$agey éves és $agem hónapos vagy!"
exit
}

beolvas() {
 if [ -f response.json ]
 then
  cat response.json | jq
 else
  echo "Nincs response.json fájl!"
  exit 1
 fi
}

szur() {
 if [ -f response.json ]
 then
  ip=$(cat response.json | jq .ip | tr -d "\"")
  hostname=$(cat response.json | jq .hostname | tr -d "\"")
  echo "Ip cím: $ip"
  echo "Hostname: $hostname"
 else
  echo "Nincs response.json fájl!"
  exit 1
 fi
}

while getopts :hqwmo: PARAM
do
 case $PARAM in
  o)
   exit
   ;;
  h)
   help
   exit
   ;;
  q)
   maidatum
   ;;
  w)
   kor
   ;;
  m)
   szur
   ;;
  :)
   echo "$OPTARG vár paramétert!"
   exit 1
   ;;
  *)
   echo "Érvénytelen paarméter!"
   exit 1
   ;;
 esac
done
shift $(($OPTIND-1))
